default_language_version:
  python: python3.14
ci:
  skip:
    - django-migration-check
    - check-untracked-migrations
exclude: .*migrations/

repos:
  # General checks and trimmers
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast  # check if files parses as valid python
      - id: check-case-conflict  # check for files causing conflict in case-insensitive filesystems
      - id: check-executables-have-shebangs  # check non-binary executables have a shebang
      - id: check-merge-conflict  # check for files with merge-conflict-stings
      - id: debug-statements  # check for debugger imports etc.
      - id: detect-private-key  # detects the presence of private keys
      - id: name-tests-test  # verify test-files are named correctly
        args: [ "--django" ]
      - id: trailing-whitespace  # trims trailing whitespace
      - id: mixed-line-ending  # Check and fix mixed line ending (only LF for compatibility)
        args: ["--fix=lf"]
      - id: check-yaml  # check yaml files for parseable syntax
      - id: check-toml  # check toml files for parseable syntax
      - id: check-json  # check json files for parseable syntax

  # Bandit - Security linter
  - repo: https://github.com/pycqa/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args: ['-iii', '-ll']  # Only report issues with high confidence and medium+ severity

  # Black - Python Code Formatter
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.3.1
    hooks:
      - id: black

  # isort - Auto sorting of imports for consistency
  - repo: https://github.com/pycqa/isort
    rev: 9.0.0a3
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # flake8 - style guide enforcement
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  - repo: https://github.com/ecugol/pre-commit-hooks-django
    rev: v0.4.0  # Use the ref you want to point at
    hooks:
    - id: check-untracked-migrations

  - repo: local
    hooks:
    - id: django-migration-check
      language: system
      name: Django Migration Check
      entry: python manage.py makemigrations --check
      pass_filenames: false