"""
Django settings for psst-secret project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import json as _json
from pathlib import Path

import environ

env = environ.Env(
    # Set casting, default value
    DEBUG=(bool, False)
)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str(
    "SECRET_KEY",
    default="django-insecure-5j3-4@f*z6mi=mu$5@64yde9ossc!-pwj9e@q&k)=xapd_b($6",  # noqa: E501
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

# Refuse to start in production with the insecure default key
if not DEBUG and SECRET_KEY.startswith("django-insecure"):
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        "You must set a proper SECRET_KEY environment variable for production."
    )

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "whispers",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whispers.middleware.NoCacheMiddleware",
]

ROOT_URLCONF = "psst_secret.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "psst_secret.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": env.db_url(
        "DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
    ),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",  # noqa: E501
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", "English"),
    ("da", "Dansk"),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


DATA_UPLOAD_MAX_MEMORY_SIZE = 50000000  # 50 MB, to allow larger secrets

# ── Security hardening (production) ──────────────────────────────────────
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

# HSTS — only enable over HTTPS (i.e., not in DEBUG)
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=not DEBUG)

# Redis — ciphertext storage (never touches disk)
REDIS_URL = env.str("REDIS_URL", default="redis://localhost:6379/0")

# Trusted proxy — set the number of proxies in front of Django so that
# get_client_ip() only trusts X-Forwarded-For from known infrastructure.
# 0 = no proxy (use REMOTE_ADDR directly); 1 = one reverse proxy; etc.
NUM_PROXIES = env.int("NUM_PROXIES", default=0)

# Per-whisper authentication options
# When True, all whispers force authentication for view/submit
# and the per-whisper option is hidden from the UI.
PSST_FORCE_AUTH_VIEW = env.bool("PSST_FORCE_AUTH_VIEW", default=False)
PSST_FORCE_AUTH_SUBMIT = env.bool("PSST_FORCE_AUTH_SUBMIT", default=False)

# Brand colors — Tailwind color palette (shade: hex)
# Override via BRAND_COLORS env var as JSON, e.g.:
#   BRAND_COLORS={"50":"#eff6ff","500":"#3b82f6","600":"#2563eb"}

_DEFAULT_BRAND_COLORS = {
    "50": "#f0fdfa",
    "100": "#ccfbf1",
    "200": "#99f6e4",
    "300": "#5eead4",
    "400": "#2dd4bf",
    "500": "#14b8a6",
    "600": "#0d9488",
    "700": "#0f766e",
    "800": "#115e59",
    "900": "#134e4a",
    "950": "#042f2e",
}
BRAND_COLORS = _json.loads(
    env.str("BRAND_COLORS", default=_json.dumps(_DEFAULT_BRAND_COLORS))
)

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": env.str("API_THROTTLE_RATE_ANON", default="60/minute"),
        "whisper_create": env.str("API_THROTTLE_RATE_CREATE", default="20/minute"),
        "whisper_view": env.str("THROTTLE_RATE_VIEW", default="30/minute"),
    },
}

# drf-spectacular — OpenAPI schema generation
SPECTACULAR_SETTINGS = {
    "TITLE": "psst-secret API",
    "DESCRIPTION": "End-to-end encrypted secret sharing. The server never sees your plaintext.",  # noqa: E501
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG" if DEBUG else "INFO",
    },
}


# Authentication with django-allauth (can be disabled if not needed) SSO
ENABLE_AUTH = env.bool("ENABLE_AUTH", default=False)
if ENABLE_AUTH:

    EMAIL_BACKEND = env.str(
        "EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend"
    )  # For development, print emails to console. Override in production.

    ACCOUNT_EMAIL_VERIFICATION = env.str(
        "ACCOUNT_EMAIL_VERIFICATION", default="none"
    )  # "mandatory", "optional", or "none"
    ENABLE_LOCAL_LOGIN = env.bool("ENABLE_LOCAL_LOGIN", default=False)
    SOCIALACCOUNT_ONLY = not ENABLE_LOCAL_LOGIN
    SOCIALACCOUNT_LOGIN_ON_GET = True  # For social auth, skip intermediate "authorize app" page and go straight to provider on GET /login/

    INSTALLED_APPS.extend(
        [
            "allauth",
            "allauth.account",
        ]
    )
    AUTHENTICATION_BACKENDS = [
        # Needed to login by username in Django admin, regardless of `allauth`
        "django.contrib.auth.backends.ModelBackend",
        # `allauth` specific authentication methods, such as login by email
        "allauth.account.auth_backends.AuthenticationBackend",
    ]
    TEMPLATES[0]["OPTIONS"]["context_processors"].append(
        "django.template.context_processors.request"
    )
    MIDDLEWARE.append("allauth.account.middleware.AccountMiddleware")
    MIDDLEWARE.append("whispers.middleware.LoginRequiredMiddleware")

    LOGIN_URL = "/login/"

    # Regex patterns for paths that skip the login requirement.
    # Paths are matched WITHOUT the leading slash.
    LOGIN_REQUIRED_EXEMPT_URLS = env.list(
        "LOGIN_REQUIRED_EXEMPT_URLS",
        default=[
            r"login/",  # custom login page
            r"accounts/.*",  # allauth auth flow
            r"i18n/.*",  # language switching
            r"static/.*",  # static files
        ],
    )
    if not PSST_FORCE_AUTH_SUBMIT:
        LOGIN_REQUIRED_EXEMPT_URLS.append(
            r"submit/.*"
        )  # allow unauthenticated submits if not forcing auth
        LOGIN_REQUIRED_EXEMPT_URLS.append(r"api/submit/.*")
    if not PSST_FORCE_AUTH_VIEW:
        LOGIN_REQUIRED_EXEMPT_URLS.append(
            r"whisper/.*"
        )  # allow unauthenticated views if not forcing auth
    # social account providers can be added as needed
    SOCIAL_AUTH_PROVIDERS = env.list("SOCIAL_AUTH_PROVIDERS", default=[])
    if SOCIAL_AUTH_PROVIDERS:
        INSTALLED_APPS.append("allauth.socialaccount")
        SOCIALACCOUNT_PROVIDERS = {}
        for provider in SOCIAL_AUTH_PROVIDERS:
            INSTALLED_APPS.append(f"allauth.socialaccount.providers.{provider}")
            SOCIALACCOUNT_PROVIDERS[provider] = env.json(
                f"{provider.upper()}_SOCIAL_AUTH_CONFIG", default={}
            )
