# Generated by Django 6.0.4 on 2026-04-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whisper',
            name='require_auth_submit',
            field=models.BooleanField(default=False, help_text='Require authentication to submit to this receive-mode request'),
        ),
        migrations.AddField(
            model_name='whisper',
            name='require_auth_view',
            field=models.BooleanField(default=False, help_text='Require authentication to view/retrieve this whisper'),
        ),
    ]
