# Generated by Django 6.0.4 on 2026-04-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispers', '0002_whisper_require_auth_submit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whisper',
            name='notify_email',
            field=models.EmailField(blank=True, default='', help_text='Email address to notify (receiver in send mode, creator in receive mode)', max_length=254),
        ),
    ]
