# Generated by Django 6.1.1 on 2026-10-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whispers", "0004_whisper_max_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="whisper",
            name="submit_token",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Write-only capability for receive-mode submit links (distinct from id)",
                null=True,
                unique=True,
            ),
        ),
    ]
