# Generated by Django 6.1.1 on 2026-10-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whispers", "0005_whisper_submit_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="HourlyWhisperStats",
            fields=[
                (
                    "bucket_start",
                    models.DateTimeField(primary_key=True, serialize=False),
                ),
                ("sends", models.PositiveBigIntegerField(default=0)),
                ("receives", models.PositiveBigIntegerField(default=0)),
                ("reveals", models.PositiveBigIntegerField(default=0)),
                ("burn_after_read", models.PositiveBigIntegerField(default=0)),
                ("expiry_5m", models.PositiveBigIntegerField(default=0)),
                ("expiry_1h", models.PositiveBigIntegerField(default=0)),
                ("expiry_1d", models.PositiveBigIntegerField(default=0)),
                ("expiry_1w", models.PositiveBigIntegerField(default=0)),
                ("expiry_1M", models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
